development:
  adapter: postgresql
  encoding: unicode
  database: unep_wcmc_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: unep_wcmc_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: unep_wcmc_production
  pool: 5

